vich_uploader:
    db_driver: orm

    mappings:
        scripts:
            uri_prefix: /images/scripts
            upload_destination: '%kernel.project_dir%/public/images/scripts'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer